services:

  frontend-dev:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/
      - VITE_API_TIMEOUT=10000
      - VITE_AUTH_ENABLED=true
      - VITE_GUEST_USER_ENABLED=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/.env:/app/.env
    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/package.json
          target: /app/package.json
          action: restart
        - path: ./frontend/vite.config.js
          target: /app/vite.config.js
          action: restart

  backend-dev:
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/app/pb_data
      - ./backend/pb_hooks:/app/pb_hooks
      - ./backend/pb_migrations:/app/pb_migrations

  nginx-dev:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./webproxy/nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-dev
      - backend-dev